version: '3.8'

services:
  mlflow_ui:
    image: python:3.9-slim
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      sh -c "pip install mlflow && 
             mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns"
    networks:
      - nlp_network

networks:
  nlp_network:
    driver: bridge
